### ISSUE TITLE
[Bug] Both agent and admin attempt to write to /tmp/application.properties

### ISSUE THREAD

**Issue by derrickmehaffy** [jslsolucoes/nginx-admin#12]
When deploying both the agent and the admin on the same machine both attempt to write to /tmp/application.properties.

After manually touching the file and giving it to the nginx-admin the agent will throw an error:

`06:11:12,880 INFO  [org.wildfly.swarm] (main) WFSWARM99999: WildFly Swarm is Ready
06:11:48,111 ERROR [io.undertow.request] (default task-3) UT005023: Exception handling request to /ping: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: java.io.IOException: File '/tmp/application.properties' cannot be written to`

I used the following command to touch the file `touch /tmp/application.properties && chmod 755 /tmp/application.properties && chown nginx-admin:nginx-admin /tmp/application.properties`

Either these need to be changed for their respective applications IE:

- nginx-agent -> `nginx-agent.properties` (And this needs to be done at the script level)
- nginx-admin -> `nginx-admin.properties` (And this needs to be done at the script level)

**Comment by jslsolucoes** [comment]
thanks for report. Bug confirmed, will be fixed in release 2.0.1 and add test case for installation on same machine.

**Comment by jslsolucoes** [comment]
Fixed. Will be released soon on 2.0.1
