### ISSUE TITLE
[Request] Would like to assist with english grammer and spelling errors.

### ISSUE THREAD

**Issue by derrickmehaffy** [jslsolucoes/nginx-admin#13]
Hey love what your doing and looking forward to using this, I noticed there are some english grammer errors that I would like to help resolve but unsure of the best means to go about doing this (not much of a java dev)

Was just wondering if you had some pointers to help try and resolve some of the issues.

**Comment by jslsolucoes** [comment]
I would love to. Do you know how to create pull requests on github ? If not i can help you with.

**Comment by derrickmehaffy** [comment]
Of course yes, I just don't know the structure of your application.

**Comment by jslsolucoes** [comment]
Basically there are two files that defines all internationalization and localization file content: 

Readme itself:
https://github.com/jslsolucoes/nginx-admin/edit/develop/README.md

Internationalization and localization application file:
https://github.com/jslsolucoes/nginx-admin/edit/develop/nginx-admin-ui/src/main/resources/messages.properties

You can check for this 2 files and fell free to modify english grammer and spelling errors or even modify some labels or texts and send me a pull request with your modifications to merge.

it`s ok for you ?

**Comment by derrickmehaffy** [comment]
That works perfect, I'll take a look and correct anything I see needs changed :)

**Comment by jslsolucoes** [comment]
Pull request merged into develop. Thanks again for revision 👍
