### ISSUE TITLE
How to get the logs?

### ISSUE THREAD

**Issue by Taymindis** [jslsolucoes/nginx-admin#2]

**Comment by jslsolucoes** [comment]
Hi, if you are talking about app logs you can find logs in /opt/nginx-admin/log . If you are talking about nginx logs you can find on "Nginx admin settings folder" that you configured in application . You can check this value on Settings menu .

**Comment by jslsolucoes** [comment]
We are closing this issue. Next release will add capability for read logs directly from interface.Thanks.
