### ISSUE TITLE
installation support - site can't be reached.

### ISSUE THREAD

**Issue by laurencefass** [jslsolucoes/nginx-admin#21]
i've pulled the image and run a container but i can't access via configured ports. i tried mapping ports to accessible ports from my host (working for default nginx container) but still not working. is there a log or something i can look at?

also: is this a container for a UI only? i.e. do i need to configure this to run with another nginx container? or is it nginx+UI? some more documentation would be really useful. 

thanks.

**Comment by jslsolucoes** [comment]
You are right about poor documentation. I will do some tests and write more documentation about how pull and start containers. 

There are 2 containers images :  
         * one for nginx-admin-agent that can be multiple instance (you can launch many (nginx + agent) instances as you want)
         * one for nginx-admin with ui thats supports management of many instances (usually you will launch just one)

Anycase can you try the following:

docker run --rm -d -p 3000:3000 -p 3443:3443 -p 3001:80 --name nginx-admin-agent-red-hat jslsolucoes/nginx-admin-agent-red-hat:2.0.3

docker run --rm -d  --link nginx-admin-agent-red-hat -p 4000:4000 -p 4443:4443 --name nginx-admin-red-hat jslsolucoes/nginx-admin-red-hat:2.0.3
