### ISSUE TITLE
pre-built docker image

### ISSUE THREAD

**Issue by laurencefass** [jslsolucoes/nginx-admin#22]
do you publish a docker image on dockerhub?

if so, have you a link?

thanks

**Comment by jslsolucoes** [comment]
Yes. Docker images it`s on dockerhub.

You can check docs on http://ng-admin.jslsolucoes.com -> Documentation -> Docker images

**Comment by laurencefass** [comment]
many thanks 

i'm not clear howto use the agent and manager together? what are their specific roles and where do i install them relative to my nginx server? i.e. on the server? 

are there any specific docker run commands to connect manager and agent?

**Comment by jslsolucoes** [comment]
There are 2 containers images :
* one for nginx-admin-agent that can be multiple instance (you can launch many (nginx + agent) instances as you want)
* one for nginx-admin with ui thats supports management of many instances (usually you will launch just one)

Anycase you can try the following:

docker run --rm -d -p 3000:3000 -p 3443:3443 -p 3001:80 --name nginx-admin-agent-red-hat jslsolucoes/nginx-admin-agent-red-hat:2.0.3

docker run --rm -d --link nginx-admin-agent-red-hat -p 4000:4000 -p 4443:4443 --name nginx-admin-red-hat jslsolucoes/nginx-admin-red-hat:2.0.3
