### ISSUE TITLE
when I start nginx via nginx-admin,I get an error that is nginx.pid does not exist

### ISSUE THREAD

**Issue by carolhuangcq** [jslsolucoes/nginx-admin#24]
![default](https://user-images.githubusercontent.com/39081923/39745589-3eeddd20-52da-11e8-927e-bce18eae6efd.png)
how to fixed it.THX

**Comment by carolhuangcq** [comment]
it's fixed.

**Comment by zx0928** [comment]
I have the same problem

**Comment by iqpkeq** [comment]
@zx0928 you can touch a file named nginx.pid;the content is nginx process id: 3247(maybe different)

**Comment by jslsolucoes** [comment]
Improvments  on scripts and prevent errors for not found in this cases
