### ISSUE TITLE
https site access  recognize domain error

### ISSUE THREAD

**Issue by iqpkeq** [jslsolucoes/nginx-admin#25]
**version**
 nginx-admin 2.0.3

**detail**
I have two website:   a.com ; b.com;
When add  above site to "List of the virtuals host",using https;
I can only visit https://a.com ,this site's webcontent;
When i input the url https://b.com; The web content is the same as A!

i look for the log in Directory,but there is no error display.The obvious abnormal condition is that I want to see the site B when i browse https://b.com but nginx-admin looks like doesn't recognize the domain with HTTPS

**Trying**
I'm trying to restart the software .but doesn't work.

**Comment by jslsolucoes** [comment]
Ok will check for this one. Are you sure that your upstream its not the same one ? In this cases both endpoints will point to same upstream thats render same content.

**Comment by iqpkeq** [comment]
@jslsolucoes I'm sure about the Upstream isn't the same. Usually i will give the site Prefix_siteA like this
