### ISSUE TITLE
https config

### ISSUE THREAD

**Issue by arebacollins** [jslsolucoes/nginx-admin#27]
It is not too clear how to do this via webGUI, and using letsencrypt, or even generating the ssl certificate from https://zerossl.com still has files that I cannot select on the uploader button of nginxadmin to create an ssl certificate. 

Any quick guide on how to do this on ubuntu + nginx-admin?

**Comment by jslsolucoes** [comment]
@arebacollins on the right side of upload browser box try select "all files". For default browser look for extensions in uppercase .CER .PEM (I`m scheduling to remove this and simplify things)

Thanks
