### ISSUE TITLE
Regarding Cluster Environment

### ISSUE THREAD

**Issue by kstan79** [jslsolucoes/nginx-admin#30]
hi,

Currently I'm using 2 nginx (active/passive) to perform reverse proxy, currently it will failed over using Heartbeat. Previously we use csync to syncronize configuration, however it is troublesome cause we need to swap server and reload server 2. 

Im curious whether we can use nginx-admin to configure server 1 and it auto replicate to server 2 + reload the configuration?

**Comment by derrickmehaffy** [comment]
@kstan79 You won't be able to use existing servers I don't believe. I'm also not sure if nginx-admin even supports clustering as it doesn't connect to existing servers
