### ISSUE TITLE
Nginx server does not start after reboot

### ISSUE THREAD

**Issue by johny-mnemonik** [jslsolucoes/nginx-admin#32]
Ngnix server has stoped after reboot.  Everytime need to start manualy from nginx admin manager web UI. When try `systemctl enable nginx-admin` have message: `nginx-admin.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig nginx-admin on`

**Comment by johny-mnemonik** [comment]
> Ngnix server any times has stoped after reboot. Everytime need to start manualy from nginx admin manager UI (status: nginx is stoped) but ngnix-admin process is works. If you give a try add ngnix server in autostart thats will any time loads nginx server welcome page instead of web site. If I kill all nginx and start nginx from web ui it works normal as reverse proxy without welcome page.
> 
> In systemd error logs: Failed to start The nginx HTTP and reverse proxy server.
> `
> 
> CODE_FILE	src/core/job.c
> CODE_FUNCTION	job_log_status_message
> CODE_LINE	773
> MESSAGE_ID	be02cf6855d2428ba40df7e9d022f03d
> PRIORITY	3
> RESULT	failed
> SYSLOG_FACILITY	3
> SYSLOG_IDENTIFIER	systemd
> UNIT	nginx.service
> _BOOT_ID	bdf880629d9a439a908c53008df90b06
> _CAP_EFFECTIVE	1fffffffff
> _CMDLINE	/usr/lib/systemd/systemd --switched-root --system --deserialize 22
> _COMM	systemd
> _EXE	/usr/lib/systemd/systemd
> _GID	0
> _HOSTNAME	localhost.localdomain
> _MACHINE_ID	8a3b100ff8ad4059a1156471a14b9b6a
> _PID	1
> _SELINUX_CONTEXT	system_u:system_r:init_t:s0
> _SOURCE_REALTIME_TIMESTAMP	1554189744863884
> _SYSTEMD_CGROUP	/
> _TRANSPORT	journal
> _UID	0
> __CURSOR	s=ff36e7ec06e14b00b2563a197bec5bb2;i=4ab;b=bdf880629d9a439a908c53008df90b06;m=2c5e3646;t=58586ffa8019f;x=4c0e555a0a72f369
> __MONOTONIC_TIMESTAMP	744371782
> __REALTIME_TIMESTAMP	1554189744865695
> `

Already finde the problem. When systeb boot Hostname servise wont start thats in Mask mode if start manualy its works. Maybe need just set up from Mask to Unmask or Enable

**Comment by johny-mnemonik** [comment]
`Hostname service`

**Comment by jslsolucoes** [comment]
Thanks for report. Nginx really doesnt start with nginx-admin because this guys run at separate unix processes, but will add  some kind of configuration like this one in next version. START_NGINX_AT_BOOT=(true|false) maybe for future

**Comment by johny-mnemonik** [comment]
Its very good news! Thank you for awesome project!

**Comment by johny-mnemonik** [comment]
> Спасибо за сообщение. Nginx действительно не запускается с nginx-admin, потому что эти парни работают на отдельных процессах Unix, но добавят какую-то конфигурацию, подобную этой, в следующей версии. START_NGINX_AT_BOOT = (true | false) возможно на будущее


Its it possible to use some human enulation script on frontend as a temporary solution?

**Comment by johny-mnemonik** [comment]
> Thanks for report. Nginx really doesnt start with nginx-admin because this guys run at separate unix processes, but will add some kind of configuration like this one in next version. START_NGINX_AT_BOOT=(true|false) maybe for future


When will the new version be approximately released?
