### ISSUE TITLE
Debian Script error 

### ISSUE THREAD

**Issue by sojab0on** [jslsolucoes/nginx-admin#52]
On trying to start teh install.sh script un Ubuntu 20.04
./install.sh: /bin/sh^M: invalid interpreter: File or folder does not exist

i am root every time when i run ./install.sh it gives that error i ran chmod +x on booth .sh scripts 
but install gives back this same error 

i have the debian based scripts

**Comment by sojab0on** [comment]
You need to convert the scripts to unix style 
i ran dos2unix on booth and now they run

**Comment by amitbauriya** [comment]
Try running this with sudo --> sed -i -e 's/\r$//' install.sh 
 chmod +x install.sh
 ./install.sh

**Comment by jslsolucoes** [comment]
the binary was fixed by now.
