### ISSUE TITLE
nginx-admin-agent Zip File

### ISSUE THREAD

**Issue by dennis-it-net** [jslsolucoes/nginx-admin#53]
Anybody has a copy of the zip files for the installation? Maybe @jslsolucoes you have a copy stashed away somewhere? Thanks!

**Comment by patrikvalentaa** [comment]
Hello, i would like to join in with @dennis-it-net . Origin storage https://bintray.com is now down and traffic has been redirected in to the https://jfrog.com, but file is not stored in same path as in bintray. @jslsolucoes, could you please share with us your zip files? thanks.

**Comment by jslsolucoes** [comment]
sorry for the late, fixed and hosted now on github folder nginx-admin-bin. Install scripts was updated as well.
