### ISSUE TITLE
Incomplete ZIP Download

### ISSUE THREAD

**Issue by Sunny99999999** [jslsolucoes/nginx-admin#62]
Hey, tried to run the script as per your site.....seems that the zip file offered is incomplete.......
Following Errors occure: 
`/opt/downloads/nginx-admin-agent-2.0.3.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /opt/downloads/nginx-admin-agent-2.0.3.zip or
        /opt/downloads/nginx-admin-agent-2.0.3.zip.zip, and cannot find /opt/downloads/nginx-admin-agent-2.0.3.zip.ZIP, period.`

Thanks for checking repo.......

RGds

sunny

**Comment by pengjiejason** [comment]
You can try package the project. P.S maven 3.5.X.
