### ISSUE TITLE
Unable to start nodes + migrate.mv.db is locked

### ISSUE THREAD

**Issue by alex-zel** [jslsolucoes/nginx-admin#8]
After installing nginx-agent and nginx-admin (on different machines) I'm unable to start an agent.

I've added a new agent and the "Test Setting" button verifies that everything is OK, however, when I go back to the main screen all I see is a blank screen with two messages:
1. No session selected yet
2. Welcome to Nginx Admin manager choose one of nginx agent node to start

Where do I select a session?
Where do I choose an nginx agent to start?
When I click the button to manage agent I get this message: "None nginx agent was configured yet, please configure one to start"
But I did configure an agent and the setting are OK.
Looking at the logs there is nothing useful.

I tried restarting the nginx-admin service and then I can't start it again (the only way I found was to restart the machine), looking at the logs I see:
```
Caused by: java.lang.IllegalStateException: The file is locked: nio:/opt/nginx-admin/database/migrate.mv.db [1.4.196/7]
...
Caused by: java.nio.channels.OverlappingFileLockException
```

I didn't change anything, followed the guide from README but it seems nothing really works.

**Comment by jslsolucoes** [comment]
docs its not fully clear yet how to use and configure things (sorry about that) i’m opening another issue to improv docs , record some shorts videos installing and using the tool. improv restarts scripts too removings this locks if exists

**Comment by jslsolucoes** [comment]
Please let me know if you successfully connect with your node . Another question . Which operating system and version is being installed your admin and agent ?

**Comment by jslsolucoes** [comment]
Fixed. Will be released soon
