### ISSUE TITLE
improv docs

### ISSUE THREAD

**Issue by jslsolucoes** [jslsolucoes/nginx-admin#9]
Improv docs how to install and use nginx-admin , record short videos too for better experience.

**Comment by derrickmehaffy** [comment]
Documentation does not clearly define how to properly setup the admin interface. There is nothing to show to install and setup MySQL nor to import the tables (unless they are created by some setup page?)

I would highly recommend an install script to automatically download and install each component and intern ask the user to change any configuration options or to install each part then provide a link for the user to setup the database ect via the web browser (MySQL settings and such)

In both cases the Database tables need to be copied over by the application.

**Comment by jslsolucoes** [comment]
Thanks for comment. New documentation and videos tutorial will be added soon as possible on next release 2.0.1.  Database is auto created in startup of application  admin. 

Mysql conf steps:

create database nginx_admin;
grant all privileges on nginx_admin.* to nginx_admin@'%' identified by 'password';
flush privileges;

go to nginx-admin folder default installation /opt/nginx-admin/conf/nginx-admin.conf and change settings to your mysql database settings like : 

NGINX_ADMIN_DB_DRIVER=mysql
NGINX_ADMIN_DB_HOST=localhost
NGINX_ADMIN_DB_PORT=3306
NGINX_ADMIN_DB_NAME=nginx_admin
NGINX_ADMIN_DB_USERNAME=nginx_admin
NGINX_ADMIN_DB_PASSWORD=password

Restart application. This steps should install your new database and up application listen on http://localhost:4000 or https://localhost:4443. You can read logs on /opt/nginx-admin/log/console.log and find about database install.

Default username and password for admin interface is : admin/admin.

Please let me know if this steps works properly in your enviroment. This settings will be added to doc front page project.

**Comment by derrickmehaffy** [comment]
It did yes I managed to figure it out prior to reading this. If you need any help with getting documentation written I wouldn't mind assisting. 

Something I would highly recommend is using Github Pages: https://pages.github.com/

**Comment by jslsolucoes** [comment]
Hot site it`s now available in beta . http://ng-admin.jslsolucoes.com.
